### ISSUE TITLE
Database Questions

### ISSUE THREAD

**Issue by DoctorJew** [SkullCrusher/Garrys-Mod-Cloud#1]
Was considering setting this up for fun, and everything is great and all frontend wise, however I am confused as to how to set up, because I am unfamiliar with the configuration you have set up in the config.ini and my.cnf files.

**Comment by SkullCrusher** [comment]
How much do you know about Apache, mysql, and php?

**Comment by DoctorJew** [comment]
I know a small amount, I'm mainly an lua person with HTML/CSS knowledge. I do have my own webserver setup however, and really am only asking to be led in the right direction.

**Comment by SkullCrusher** [comment]
I'm definitely willing to help you out to get it running for you. So originally this was running on IIS which is Windows Server version of a web serve like Apache. So those configuration files were based around clustering for MySQL, it's not really required but it improves performance greatly. You won't need those so I removed them, sorry that I didn't remove them before now.

In a more general terms of how to set this up sorta depends but overall it has the same idea. Here are some steps to start with: 

1. Install MySQL server if it's not already. It is used for login, file storage (on v1), and download link... linking. There is a SQL install script in the repository you can use to populate it. Create a new account on MySQL (I named mine "GarrysModCloud") with a good just purely random password. Give the account select, update, delete access to the database. You may need to give it a few other permissions but less is better. Inside the PHP files I declare the username and password ("'GarrysModCloud', 'QvKLnwQ9BW3tHUte'") replace that with your account. It needs to be done for all of the php files where I do any MySQL requests.

2. You need Steam Web API Key for the authentication (https://steamcommunity.com/dev) which allows you to authenticate the people logging in on the website. Get one and swap out the current one for it.

3. Copy the source files into a web server, IIS or Apache are standard. You should be able to navigate to it on the homepage at least (index.php). If it's a linux based system you will have to give it rw access to the files folder.

4. I would check that the lua runs and then swap out the url for garrysmodcloud with where ever it's syncing to.

So this should be a good starting point, try this and tell me what issues you run into and we can fix them.

**Comment by DoctorJew** [comment]
I already had everything else good to go, the MySQL database was my only issue.

Alright, everything works perfectly fine. However, tweaked the timer in CallGameTimer() to 5 minutes because 60 seconds was far too frequent to be checking files. Maybe wouldn't be an issue if someone didn't have any, but if you're someone like me who has hundreds to run through the small stutter every 60 seconds would be annoying.

Anyways, for what it's worth all of the functionality currently as is I've put up [here](https://thedoctorjew.com/cloud/). But I've heavily modified the theme to use Bootstrap, and no it's not responsive at the moment 😫

**Comment by SkullCrusher** [comment]
I set my production to 3 minutes for update but I think it executes asynchronous so not sure if it will stutter. I am glad everything works for you, if you have any issues let me know and I'll see what I can do.

Closing issue, reopen if not resolved.
